// <auto-generated />
namespace KEC.Curation.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ToCuratioUiDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToCuratioUiDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201803090830017_ToCuratioUiDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
