// <auto-generated />
using KEC.Curation.Data.Database;
using KEC.Curation.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KEC.Curation.Data.Migrations
{
    [DbContext(typeof(CurationDataContext))]
    [Migration("20180205161341_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KEC.Curation.Data.Models.CuratorAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedBy");

                    b.Property<string>("Assignee");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Notes");

                    b.Property<int>("PublicationSectionId");

                    b.HasKey("Id");

                    b.HasIndex("PublicationSectionId")
                        .IsUnique();

                    b.ToTable("CuratorAssignments");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.CuratorCreation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("FirstName");

                    b.Property<string>("GUID");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("CuratorCreations");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.CuratorType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TypeName");

                    b.HasKey("Id");

                    b.ToTable("CuratorTypes");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorName");

                    b.Property<string>("CertificateNumber");

                    b.Property<string>("CertificateUrl");

                    b.Property<DateTime>("CompletionDate");

                    b.Property<DateTime>("CreatedTimeUtc");

                    b.Property<string>("Description");

                    b.Property<int>("GradeId");

                    b.Property<string>("ISBNNumber");

                    b.Property<string>("KICDNumber");

                    b.Property<int?>("LevelId");

                    b.Property<string>("MimeType");

                    b.Property<DateTime>("ModifiedTimeUtc");

                    b.Property<string>("Owner");

                    b.Property<decimal>("Price");

                    b.Property<string>("PublisherName");

                    b.Property<int>("Stage");

                    b.Property<int>("SubjectId");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.PublicationSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Owner");

                    b.Property<int>("PublicationId");

                    b.Property<string>("SectionDescription");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("PublicationSections");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.PublicationStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PublicationStages");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.PublicationStageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionTaken");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Notes");

                    b.Property<string>("Owner");

                    b.Property<int>("PublicationId");

                    b.Property<int>("PublicationStageId");

                    b.Property<int?>("PublicationStageId1");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("PublicationStageId1");

                    b.ToTable("PublicationStageLogs");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SubjectTypeId");

                    b.HasKey("Id");

                    b.HasIndex("SubjectTypeId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.SubjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SubjectTypes");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.CuratorAssignment", b =>
                {
                    b.HasOne("KEC.Curation.Data.Models.PublicationSection", "PublicationSection")
                        .WithOne("CuratorAssignment")
                        .HasForeignKey("KEC.Curation.Data.Models.CuratorAssignment", "PublicationSectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.Publication", b =>
                {
                    b.HasOne("KEC.Curation.Data.Models.Level", "Level")
                        .WithMany("Publications")
                        .HasForeignKey("LevelId");

                    b.HasOne("KEC.Curation.Data.Models.Subject", "Subject")
                        .WithMany("Publications")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.PublicationSection", b =>
                {
                    b.HasOne("KEC.Curation.Data.Models.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.PublicationStageLog", b =>
                {
                    b.HasOne("KEC.Curation.Data.Models.Publication", "Publication")
                        .WithMany("PublicationStageLogs")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KEC.Curation.Data.Models.PublicationStage", "PublicationStage")
                        .WithMany("PublicationStageLogs")
                        .HasForeignKey("PublicationStageId1");
                });

            modelBuilder.Entity("KEC.Curation.Data.Models.Subject", b =>
                {
                    b.HasOne("KEC.Curation.Data.Models.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
